### PR TITLE
Make CJK chars work finally

### LINKED ISSUE #140: CJK character is not rendered correctly
Here is the file content:

```
$ cat test                            
中文测试
```

Open  it with uivonim:

Enviornment:

- Arch Linux
- Uivonim v0.28.0.24.gd23b6ea
- Neovim 0.4.4

### PR DESCRIPTION
**Pull request by smolck**
Still needs some work but I'm fairly confident I can finally fix #140 with this.

@SilverRainZ would you mind giving this branch a test? The chars (both Latin and CJK) aren't displayed _perfectly_ (still need some tweaking on that front I think), but it seems to mostly display CJK chars properly from my testing.

### CODE REVIEW

**Comment by SilverRainZ** [comment]
wow, In my field of vision, all Chinese chars rendered correctly, emoji is okay too.



[](url)

**Comment by SilverRainZ** [comment]
There are still some words that can not be correctly rendered, hope it is helpful for you debgging:

- **实**习
- 加**载**
- **直**接
- 同**样**

**Comment by smolck** [comment]
> There are still some words that can not be correctly rendered, hope it is helpful for you debgging:
> 
>     * **实**习
> 
>     * 加**载**
> 
>     * **直**接
> 
>     * 同**样**

@SilverRainZ Would you mind explaining what renders incorrectly about those characters? They seem to look fine on my end:

chars

The only reason I'd guess they wouldn't render correctly would be if there were lots of different chars in use in a single file (something I guess could happen pretty often?), and the font atlas could perhaps get filled, causing rendering issues. Might need to work in some way of knowing when that happens and increasing the font atlas size if necessary; but I don't know if that's what's happening for you there?

**Comment by SilverRainZ** [comment]
The original text is `是这个**样**子的`, but this case only appears one time and now I can reproduce it.

**Comment by clason** [comment]
Just to make sure, it's the bold markup `** ... **` that is the issue? It works for the same character without it?

**Comment by SilverRainZ** [comment]
> Just to make sure, it's the bold markup `** ... **` that is the issue? It works for the same character without it?

Sorry, it is just for emphasizing, and does not related to this issue.

**Comment by smolck** [comment]
Hmm, well since you can't reproduce it anymore, I'll just go ahead and merge this. Feel free to open an issue if the problem re-appears/persists!

**Comment by smolck** [comment]
> The original text is `是这**样**子的`, but this case only appears one time and now I can not reproduce it.
> 
> 

Just a note, I think I was able to fix the issue you were running into with https://github.com/smolck/uivonim/commit/3f26610fd0e0e3bcb48cbd1f0b1f60a1becbab85; for me it looked something like this, although it varied:



In that screenshot you can also see the font atlas, and how the char gets cut off at the edge of the canvas there, causing the char to appear incorrectly. A look at the code revealed I had forgotten to account for double width chars at the edge of the font atlas, and that was the result. So should be fixed in that commit I linked above (and thus on master).

**Pull request merged**
